### ISSUE TITLE
Getting Fatal error upon trying to edit field

### ISSUE THREAD

**Issue by tamerzg** [mlibrary/Entity-Reference-Exposed-Filters#1]
When trying to edit the field (field_at_centre: Content) Content: Entity Reference Exposed Filters Node Titles in Views I am getting
Fatal error: Unsupported operand types in /Library/WebServer/Documents/web/core/modules/views/src/Plugin/views/filter/InOperator.php on line 182
Call Stack

**Comment by vagabundeo** [comment]
outdated. use https://www.drupal.org/project/issues/entity_reference_exposed_filters?status=All&categories=All
