### ISSUE TITLE
Warning in ERefNodeTitles.php Line #114

### ISSUE THREAD

**Issue by eknapier** [mlibrary/Entity-Reference-Exposed-Filters#4]
Warning: array_keys() expects parameter 1 to be array, null given in Drupal\entity_reference_exposed_filters\Plugin\views\filter\EREFNodeTitles->defineOptions() (line 114 of modules/custom/Entity-Reference-Exposed-Filters-master/src/Plugin/views/filter/EREFNodeTitles.php).

I get the above error on the View I have created with this plugin,  the error appears nearly every time I make an exposed filter selection. I have submitted a PR to address the issue: https://github.com/mlibrary/Entity-Reference-Exposed-Filters/pull/3

**Comment by eknapier** [comment]
I believe this PR submitted will take care of all instances of Warnings getting kicked out due to no relationships being set, similar to what this commit is addressing: https://github.com/mlibrary/Entity-Reference-Exposed-Filters/commit/dca9b0f2355a902fcb22bb0948975d270cc0c470

**Comment by eknapier** [comment]
Has this module been updated/replaced by https://www.drupal.org/project/entity_reference_views_select?

**Comment by vagabundeo** [comment]
outdated. use https://www.drupal.org/project/issues/entity_reference_exposed_filters?status=All&categories=All
